// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6f8bf452DecodeInventoryServiceAppModels(in *jlexer.Lexer, out *Inventory) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "productId":
			out.ProductId = int64(in.Int64())
		case "sku":
			out.SKU = int32(in.Int32())
		case "purchasePrice":
			out.PurchasePrice = int32(in.Int32())
		case "salePrice":
			out.SalePrice = int32(in.Int32())
		case "createdAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updatedAt":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6f8bf452EncodeInventoryServiceAppModels(out *jwriter.Writer, in Inventory) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"productId\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ProductId))
	}
	{
		const prefix string = ",\"sku\":"
		out.RawString(prefix)
		out.Int32(int32(in.SKU))
	}
	{
		const prefix string = ",\"purchasePrice\":"
		out.RawString(prefix)
		out.Int32(int32(in.PurchasePrice))
	}
	{
		const prefix string = ",\"salePrice\":"
		out.RawString(prefix)
		out.Int32(int32(in.SalePrice))
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Inventory) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6f8bf452EncodeInventoryServiceAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Inventory) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6f8bf452EncodeInventoryServiceAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Inventory) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6f8bf452DecodeInventoryServiceAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Inventory) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6f8bf452DecodeInventoryServiceAppModels(l, v)
}
