ENVIRONMENT: "local"
APP_NAME: "inventory-service"
SQL_CONFIG:
    USERNAME: "testuser"
    PASSWORD: "testpassword"
    HOST: "localhost"
    PORT: "3306"
    DATABASE: "testdb"
    MAX_LIFE_TIME: 3
    MAX_OPEN_CONNS: 10
    MAX_IDLE_CONNS: 10
HTTP_SERVER:
    PORT: 3003
    READ_TIMEOUT_MS: 1000
    WRITE_TIMEOUT_MS: 1000
PRODUCT_UPDATE_TOPIC:
    NAME: "product_update"
INVENTORY_UPDATE_TOPIC:
    NAME: "inventory_update"
