ENVIRONMENT: "dev"
APP_NAME: "inventory-service"
SQL_CONFIG:
    USERNAME: "testuser"
    PASSWORD: "testpassword"
    HOST: "docker.for.mac.localhost"
    PORT: "3306"
    DATABASE: "testdb"
    MAX_LIFE_TIME: 3
    MAX_OPEN_CONNS: 10
    MAX_IDLE_CONNS: 10
HTTP_SERVER:
    PORT: 3003
