ENVIRONMENT: "dev"
APP_NAME: "search-service"
GRPC_SERVER:
    PORT: 9004
ELASTIC_SEARCH:
    ADDRESS: http://elasticsearch:9200
    INDEX_NAME: searchindex
KAFKA_CONFIG:
    SERVERS: "kafka:19092"
    GROUP_ID: "inventory_service"
PRODUCT_UPDATE_TOPIC:
    NAME: "product_update"
